[package]
name = "publish"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A first publish to test"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
