[package]
name = "macros"
version = "0.1.0"
edition = "2021"


[workspace]
members = ["hello_macro", "hello_macro_derive"]

[dependencies]
hello_macro = { path = "./hello_macro/" }
hello_macro_derive = { path = "./hello_macro_derive/" }
